### ISSUE TITLE
HDFS DISK SPACE ISSUE

### ISSUE THREAD

**Issue by ashishsoni** [randerzander/docker-hdp#3]
Not sure but ambari is keep complaining that disk is used 99% not sure why

**Comment by jrevillard** [comment]
I have the same issue. Any advice please ? (I'm using the single node configuration)

Best,
Jerome

**Comment by jrevillard** [comment]
Ok I solved it. The problem comes from the "dfs.datanode.du.reserved" parameter the HDFS service which was reserving too much space for the non HDFS data. Reducing this to the dafaut value (10G: 1073741824) solved the problem for me. Of course this parameter depends on your docker image disk size: Disk Usage (Non DFS Used) 	8.4 GB / 13.7 GB (61.38%)

**Comment by randerzander** [comment]
Thanks for the explanation of your resolution, @jrevillard. I think the takeaway is that this image (and using it) requires significant (20GB+) disk space on your docker host.
