### ISSUE TITLE
getting error for sed

### ISSUE THREAD

**Issue by vamsi77874** [randerzander/docker-hdp#6]
sed -i "s/\${ambariSchemaVersion}/2.4.2.0/g" /Ambari-DDL-Postgres-CREATE.sql 

the above command getting executed as postgres but since it doesn't have access to permission to / folder, it is permission denied error
sed: couldn't open temporary file Permission denied

**Comment by mferlay** [comment]
The same, so it's not possible to use it because it does not let create the role ambari.

**Comment by sarath-mec** [comment]
Postgres Latest Docker image has changes due to which postgres user is created and has less privileges as root. So in shell the sed command don't have rights to edit the file

Additionally, as of docker-library/postgres#253, these initialization scripts are run as the postgres user (or as the "semi-arbitrary user" specified with the --user flag to docker run; see the section titled "Arbitrary --user Notes" for more details).

I have modified DockerFile and script.sh in containers/postgres folder as follows and it worked. Basically moved statements in script.sh which is runas postgres to Dockerfile. Moved lines are commented in scripts.sh

==================================================
FROM postgres
ARG DDL_URL
RUN apt-get update -y
RUN apt-get install sudo
RUN apt-get install -y wget
RUN wget ${DDL_URL}
RUN chmod 777 /
RUN chmod 777 /tmp
RUN chmod 777 Ambari-DDL-Postgres-CREATE.sql
RUN sed -i "s/\${ambariSchemaVersion}/2.4.2.0/g" Ambari-DDL-Postgres-CREATE.sql
ADD pg_hba.conf /
RUN chown postgres /pg_hba.conf
RUN mv /pg_hba.conf /var/lib/postgresql/data/
ADD scripts/* /docker-entrypoint-initdb.d/
==================================================

#!/bin/bash
set -e
whoami
#sed -i "s/\${ambariSchemaVersion}/2.4.2.0/g" /Ambari-DDL-Postgres-CREATE.sql
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    create database ambari;
    create user ambari with password 'dev';
    GRANT ALL PRIVILEGES ON DATABASE ambari TO ambari;
    CREATE SCHEMA ambari AUTHORIZATION ambari;
    ALTER SCHEMA ambari OWNER TO ambari;
    ALTER SCHEMA public OWNER to ambari;
    ALTER ROLE ambari SET search_path to 'ambari', 'public';
    \connect ambari ambari;
    \i Ambari-DDL-Postgres-CREATE.sql 
EOSQL
#chown postgres /pg_hba.conf
#mv /pg_hba.conf /var/lib/postgresql/data/
==================================================

**Comment by randerzander** [comment]
Thanks for the discussion, all. I believe I fixed this with the latest push to master with upgrade to HDP 2.6.

If you continue running into this problem, please re-open this or another issue.
